# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gwoekga-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'naveridlogin-sdk-ios'
  pod 'YPImagePicker'
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Cosmos', '~> 22.1'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  # Pods for Gwoekga-ios

end
